steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login -u=$$DOCKERUSERNAME -p=$$DOCKERPASSWORD
        docker build -t mdnurakmal/project1-nginx-reverse-proxy:latest . 
        docker push mdnurakmal/project1-nginx-reverse-proxy:latest
    secretEnv: [ 'DOCKERUSERNAME', 'DOCKERPASSWORD' ]
  
  # # deploy container image to GKE
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #   - run
  #   - --filename=deployment.yaml
  #   - --location=my-kubernetes-cluster
  #   - --cluster=us-central1-c
  #   - --image=mdnurakmal/project1-nginx-reverse-proxy:latest

availableSecrets:
  secretManager:
    - versionName: projects/test-327905/secrets/DOCKERUSERNAME/versions/1
      env: 'DOCKERUSERNAME'
    - versionName: projects/test-327905/secrets/DOCKERPASSWORD/versions/1
      env: 'DOCKERPASSWORD'


options:
  logging: CLOUD_LOGGING_ONLY