apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ws-reverse-proxy
  name: ws-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-reverse-proxy
  template:
    metadata:
      labels:
        app: ws-reverse-proxy
    spec:
      containers:
        - image: mdnurakmal/project1-nginx-reverse-proxy:latest
          name: ws-reverse-proxy
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
---


apiVersion: v1
kind: Service
metadata:
  name: ws-reverse-proxy-http-service
spec:
  selector:
    app: ws-reverse-proxy
  type: NodePort
  ports:
    - name: my-http-port
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ws-reverse-proxy-service
spec:
  selector:
    app: ws-reverse-proxy
  type: NodePort
  ports:
    - name: my-https-port
      port: 443
      targetPort: 443