serverBlock: |-
  server {
      listen 443 ;

      location / {
          proxy_pass http://wschat.mdnurakmal.com;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection upgrade;
      }
  }


containerSecurityContext.runAsNonRoot: false

containerSecurityContext.runAsUser: 0